stages:
  load_data: 
    cmd: python src/stage_01_load_extract_save.py --config=config.yaml
    deps:
      - config/config.yaml
      - src/utils/all_utils.py
      - src/stage_01_load_extract_save.py
    outs:
      - artifacts/clean_data/X.npy
      - artifacts/clean_data/Y.npy