stages:
  load_extract_save: 
    cmd: python src/stage_01_load_extract_save.py --config=config.yaml
    deps:
      - config/config.yaml
      - src/utils/all_utils.py
      - src/stage_01_load_extract_save.py
    outs:
      - artifacts/clean_data/X.npy
      - artifacts/clean_data/Y.npy

  train_test_split_save:
    cmd: python/src/stage_02_train_test_split_save.py --config=config.yaml --params=params.yaml
    deps:
      - artifacts/clean_data/X.npy
      - artifacts/clean_data/Y.npy
      - params.yaml
      - stage_02_train_test_split_save.py
    outs:
      - artifacts/train_data/X_train.npy
      - artifacts/train_data/Y_train.npy
      - artifacts/test_data/X_test.npy
      - artifacts/test_data/Y_test.npy