artifacts:
  ARTIFACTS_DIR: artifacts
  TRAINED_MODEL_DIR: model
  TRAINED_MODEL_NAME: audio_mnist_classifier.h5
  CHECKPOINT_DIR: checkpoints
  BASE_LOG_DIR: base_model_dir
  TENSORBOARD_ROOT_LOG_DIR: tensorboard_log_dir

source_data_dir:
  - artifacts/data

local_data_dir:
  - clean_data
  - train_data
  - test_data