# Add CI/CD Steps Here
name: audio_mnist_classification
on: [push]
jobs:
  run:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Our ML Workflow Commands
          sudo apt-get install libsndfile1
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install kaggle

          mv kaggle.json /home/runner/.kaggle
          
          # Run the stages
          dvc repro -v

          # Print this message in the report
          echo "Audio MNIST's Classifier Neural Network's Confusion Matrix" >> report.md

          # Display the confusion matrix image in the report
          cml-publish "confusion_matrix.png" --md >> report.md

          cml-send-comment report.md